//
// Created by Christian Reiswich on 2/3/25.
//

#ifndef SRC_CPP_STUDENT_MULTIPLEDEFINITIONS_H
#define SRC_CPP_STUDENT_MULTIPLEDEFINITIONS_H
#endif //SRC_CPP_STUDENT_MULTIPLEDEFINITIONS_H

int polynom(int x);
